name: Production
on:
  push:
    branches:
      - main
jobs:
  synching: Synching
  runs-on: self-hosted
  steps:
    - name: Pulling code base from remote branch to local branch
      run: |
        git checkout main
        git pull origin main

  building:
    name: Building
    needs: synching
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm i
      - run: npx nx affected --target=build --parallel=3
